Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/teabook/teabook/lib64/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
keys = ['imagetyp','OBJECT' , 'EXPTIME' , 'ALFLTID' , 'FAFLTID' , 'FBFLTID']
ic1 = ImageFileCollection(directory, keywords=keys) # only keep track of keys
ic1.summary.colnames
print(keys)
------------------

[0;31m-------------------------------------[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-1-08b5a2f294c9>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mkeys[0m [0;34m=[0m [0;34m[[0m[0;34m'imagetyp'[0m[0;34m,[0m[0;34m'OBJECT'[0m [0;34m,[0m [0;34m'EXPTIME'[0m [0;34m,[0m [0;34m'ALFLTID'[0m [0;34m,[0m [0;34m'FAFLTID'[0m [0;34m,[0m [0;34m'FBFLTID'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mic1[0m [0;34m=[0m [0mImageFileCollection[0m[0;34m([0m[0mdirectory[0m[0;34m,[0m [0mkeywords[0m[0;34m=[0m[0mkeys[0m[0;34m)[0m [0;31m# only keep track of keys[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mic1[0m[0;34m.[0m[0msummary[0m[0;34m.[0m[0mcolnames[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mprint[0m[0;34m([0m[0mkeys[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'ImageFileCollection' is not defined
NameError: name 'ImageFileCollection' is not defined

